//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fireman_Systemn
{
    using System;
    using System.Collections.Generic;
    
    public partial class FireTrucks
    {
        public int fire_truck_id { get; set; }
        public string model { get; set; }
        public double water_capacity { get; set; }
        public double staff_capacity { get; set; }
        public double available_water { get; set; }
        public double fuel_capacity { get; set; }
        public double available_fuel { get; set; }
        public int answered_cases { get; set; }
        public virtual Teams Teams { get; set; }
    }
}
