//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fireman_Systemn
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FiremanSysEntities : DbContext
    {
        public FiremanSysEntities()
            : base("name=FiremanSysEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cases> Cases { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<FireTrucks> FireTrucks { get; set; }
        public virtual DbSet<Teams> Teams { get; set; }
    }
}
