//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fireman_Systemn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teams
    {
        public int team_id { get; set; }
        public string team_name { get; set; }
        public string number_of_members { get; set; }
        public int choosen_fire_truck { get; set; }
        public int number_of_answered_cases { get; set; }
        public string is_team_active { get; set; }
        public string is_team_busy { get; set; }
    }
}
